name = "QuartzGetWindow"
uuid = "400ccb3a-1b84-4e00-b4ec-2df3d4dff5ac"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Replay = "dd78c5bf-19c4-4e9c-96ce-c3ec745c7812"

[compat]
Replay = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
